# Generated by Django 5.0.3 on 2024-03-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=500, unique=True)),
                ('head_office_address', models.CharField(max_length=255)),
                ('factory_addresses', models.TextField()),
                ('email_addresses', models.TextField()),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('managing_director_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/products')),
                ('is_availble', models.BooleanField(default=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
