# Generated by Django 5.0.3 on 2024-03-27 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_company_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='category',
            new_name='website',
        ),
    ]
