# Generated by Django 5.0.3 on 2024-03-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_category_company_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='photos/default.png', upload_to='photos/logos'),
        ),
    ]
