# Generated by Django 5.0.3 on 2024-03-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_newsarticle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='publication_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
