# Generated by Django 5.0 on 2024-04-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_newsarticle_publication_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(max_length=100)),
                ('education', models.TextField()),
                ('description', models.TextField()),
                ('professional_history', models.TextField(blank=True, null=True)),
                ('business_history', models.TextField(blank=True, null=True)),
                ('achievement', models.TextField(blank=True, null=True)),
                ('awards', models.TextField(blank=True, null=True)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('role_in_industries', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='leader_images/')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
