# Generated by Django 5.0.6 on 2024-05-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_company_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_name', models.CharField(max_length=60)),
                ('owner_name', models.CharField(max_length=60)),
                ('responsibility', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=155)),
                ('contact', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=60)),
                ('Extra', models.CharField(max_length=100)),
            ],
        ),
    ]
