# Generated by Django 5.0.6 on 2024-07-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_company_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('content', models.TextField()),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('social_link', models.URLField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='photos/events_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='photos/events_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='photos/events_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='photos/events_images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='photos/events_images/')),
            ],
        ),
    ]
