# Generated by Django 5.0.6 on 2024-07-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_image_image2_image_image3_video_video2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/images2/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/images3/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video2',
            field=models.FileField(blank=True, null=True, upload_to='gallery/videos2/'),
        ),
    ]
