# Generated by Django 5.0.3 on 2024-05-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_category_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='company',
            name='serial_no',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
