# Generated by Django 5.0.3 on 2024-05-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_company_extra_remove_company_serial_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon/')),
                ('contant', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates_category/')),
            ],
        ),
    ]
