# Generated by Django 5.0.6 on 2024-06-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_category_content_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='Short_contant',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
