# Generated by Django 5.0.3 on 2024-05-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/blog_images/'),
        ),
    ]
