# Generated by Django 5.0.6 on 2024-05-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0005_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='big_text',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='small_text',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
