# Generated by Django 5.0.6 on 2024-05-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0006_alter_home_big_text_alter_home_small_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/Slide Video'),
        ),
    ]
