# Generated by Django 5.0.6 on 2024-05-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0007_home_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/Slide Video')),
            ],
        ),
        migrations.RemoveField(
            model_name='home',
            name='video',
        ),
    ]
