# Generated by Django 5.0.6 on 2024-06-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0008_video_homepage_remove_home_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_homepage',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
