# Generated by Django 5.0.6 on 2024-07-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0009_alter_video_homepage_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management_Massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=105)),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='Admin_images/')),
                ('text', models.TextField(help_text='Write the CEO/Director Massage')),
                ('others', models.CharField(max_length=255)),
            ],
        ),
    ]
