# Generated by Django 5.0.3 on 2024-05-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_remove_job_link_job_duration_job_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
