# Generated by Django 5.0.3 on 2024-05-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
