# Generated by Django 5.0.3 on 2024-05-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_resume_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
